/*
 * Nodeum API
 * # About  This document describes the Nodeum API version 2:  If you are looking for any information about the product itself, reach the product website https://www.nodeum.io. You can also contact us at this email address : info@nodeum.io  # Filter parameters When browsing a list of items, multiple filter parameters may be applied. Some operators can be added to the value as a prefix:  - `=` value is equal. Default operator, may be omitted  - `!=` value is different  - `>` greater than  - `>=` greater than or equal  - `<` lower than  - `>=` lower than or equal  - `><` included in list, items should be separated by `|`  - `!><` not included in list, items should be separated by `|`  - `~` pattern matching, may include `%` (any characters) and `_` (one character)  - `!~` pattern not matching, may include `%` (any characters) and `_` (one character)  
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.nodeum.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TaskSchedule
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-12-11T14:27:44.769Z[GMT]")
public class TaskSchedule {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_TASK_ID = "task_id";
  @SerializedName(SERIALIZED_NAME_TASK_ID)
  private Integer taskId;

  public static final String SERIALIZED_NAME_RRULE = "rrule";
  @SerializedName(SERIALIZED_NAME_RRULE)
  private String rrule;

  public static final String SERIALIZED_NAME_DONE = "done";
  @SerializedName(SERIALIZED_NAME_DONE)
  private Boolean done;

  public static final String SERIALIZED_NAME_NEXT = "next";
  @SerializedName(SERIALIZED_NAME_NEXT)
  private String next;

  public static final String SERIALIZED_NAME_MISSED_COUNT = "missed_count";
  @SerializedName(SERIALIZED_NAME_MISSED_COUNT)
  private Integer missedCount;

  public static final String SERIALIZED_NAME_SKIPPED_COUNT = "skipped_count";
  @SerializedName(SERIALIZED_NAME_SKIPPED_COUNT)
  private Integer skippedCount;

  public static final String SERIALIZED_NAME_MISSED_LAST = "missed_last";
  @SerializedName(SERIALIZED_NAME_MISSED_LAST)
  private String missedLast;

  public static final String SERIALIZED_NAME_MISSED_FIRST = "missed_first";
  @SerializedName(SERIALIZED_NAME_MISSED_FIRST)
  private String missedFirst;


   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getId() {
    return id;
  }




  public TaskSchedule taskId(Integer taskId) {
    
    this.taskId = taskId;
    return this;
  }

   /**
   * Get taskId
   * @return taskId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "16", value = "")

  public Integer getTaskId() {
    return taskId;
  }


  public void setTaskId(Integer taskId) {
    this.taskId = taskId;
  }


  public TaskSchedule rrule(String rrule) {
    
    this.rrule = rrule;
    return this;
  }

   /**
   * Get rrule
   * @return rrule
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "DTSTART;TZID=Europe/Paris:20190705T085000 RRULE:FREQ=WEEKLY", value = "")

  public String getRrule() {
    return rrule;
  }


  public void setRrule(String rrule) {
    this.rrule = rrule;
  }


  public TaskSchedule done(Boolean done) {
    
    this.done = done;
    return this;
  }

   /**
   * Get done
   * @return done
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "")

  public Boolean getDone() {
    return done;
  }


  public void setDone(Boolean done) {
    this.done = done;
  }


   /**
   * Get next
   * @return next
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2019-10-11T15:00:00Z", value = "")

  public String getNext() {
    return next;
  }




   /**
   * Get missedCount
   * @return missedCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2", value = "")

  public Integer getMissedCount() {
    return missedCount;
  }




   /**
   * Get skippedCount
   * @return skippedCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0", value = "")

  public Integer getSkippedCount() {
    return skippedCount;
  }




   /**
   * Get missedLast
   * @return missedLast
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2019-10-11T13:00:00Z", value = "")

  public String getMissedLast() {
    return missedLast;
  }




   /**
   * Get missedFirst
   * @return missedFirst
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2019-10-11T11:00:00Z", value = "")

  public String getMissedFirst() {
    return missedFirst;
  }




  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaskSchedule taskSchedule = (TaskSchedule) o;
    return Objects.equals(this.id, taskSchedule.id) &&
        Objects.equals(this.taskId, taskSchedule.taskId) &&
        Objects.equals(this.rrule, taskSchedule.rrule) &&
        Objects.equals(this.done, taskSchedule.done) &&
        Objects.equals(this.next, taskSchedule.next) &&
        Objects.equals(this.missedCount, taskSchedule.missedCount) &&
        Objects.equals(this.skippedCount, taskSchedule.skippedCount) &&
        Objects.equals(this.missedLast, taskSchedule.missedLast) &&
        Objects.equals(this.missedFirst, taskSchedule.missedFirst);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, taskId, rrule, done, next, missedCount, skippedCount, missedLast, missedFirst);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaskSchedule {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    taskId: ").append(toIndentedString(taskId)).append("\n");
    sb.append("    rrule: ").append(toIndentedString(rrule)).append("\n");
    sb.append("    done: ").append(toIndentedString(done)).append("\n");
    sb.append("    next: ").append(toIndentedString(next)).append("\n");
    sb.append("    missedCount: ").append(toIndentedString(missedCount)).append("\n");
    sb.append("    skippedCount: ").append(toIndentedString(skippedCount)).append("\n");
    sb.append("    missedLast: ").append(toIndentedString(missedLast)).append("\n");
    sb.append("    missedFirst: ").append(toIndentedString(missedFirst)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

