/*
 * Nodeum API
 * Nodeum API  # Filter parameters When browsing a list of items, multiple filter parameters may be applied. Some operators can be added to the value as a prefix:  - `=` value is equal. Default operator, may be omitted  - `!=` value is different  - `>` greater than  - `>=` greater than or equal  - `<` lower than  - `>=` lower than or equal  - `><` included in list, items should be separated by `|`  - `!><` not included in list, items should be separated by `|`  - `~` pattern matching, may include `%` (any characters) and `_` (one character)  - `!~` pattern not matching, may include `%` (any characters) and `_` (one character)  
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Container
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-09-16T09:57:17.206Z")
public class Container {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("comment")
  private String comment = null;

  @SerializedName("quota_total_size")
  private Integer quotaTotalSize = null;

  @SerializedName("quota_on_cache")
  private Integer quotaOnCache = null;

  @SerializedName("stat_total_files")
  private Integer statTotalFiles = null;

  @SerializedName("stat_total_size")
  private Integer statTotalSize = null;

  @SerializedName("stat_size_on_cache")
  private Integer statSizeOnCache = null;

  /**
   * Gets or Sets guestRight
   */
  @JsonAdapter(GuestRightEnum.Adapter.class)
  public enum GuestRightEnum {
    NONE("none"),
    
    READ("read"),
    
    READ_WRITE("read_write");

    private String value;

    GuestRightEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static GuestRightEnum fromValue(String text) {
      for (GuestRightEnum b : GuestRightEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<GuestRightEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final GuestRightEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public GuestRightEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return GuestRightEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("guest_right")
  private GuestRightEnum guestRight = null;

  @SerializedName("last_update")
  private String lastUpdate = null;

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "100", value = "")
  public Integer getId() {
    return id;
  }

  public Container name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "my-container", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Container comment(String comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  @ApiModelProperty(example = "Read only container for random stuff", value = "")
  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public Container quotaTotalSize(Integer quotaTotalSize) {
    this.quotaTotalSize = quotaTotalSize;
    return this;
  }

   /**
   * Get quotaTotalSize
   * @return quotaTotalSize
  **/
  @ApiModelProperty(value = "")
  public Integer getQuotaTotalSize() {
    return quotaTotalSize;
  }

  public void setQuotaTotalSize(Integer quotaTotalSize) {
    this.quotaTotalSize = quotaTotalSize;
  }

  public Container quotaOnCache(Integer quotaOnCache) {
    this.quotaOnCache = quotaOnCache;
    return this;
  }

   /**
   * Get quotaOnCache
   * @return quotaOnCache
  **/
  @ApiModelProperty(value = "")
  public Integer getQuotaOnCache() {
    return quotaOnCache;
  }

  public void setQuotaOnCache(Integer quotaOnCache) {
    this.quotaOnCache = quotaOnCache;
  }

   /**
   * Get statTotalFiles
   * @return statTotalFiles
  **/
  @ApiModelProperty(example = "99301", value = "")
  public Integer getStatTotalFiles() {
    return statTotalFiles;
  }

   /**
   * Get statTotalSize
   * @return statTotalSize
  **/
  @ApiModelProperty(example = "6145076462", value = "")
  public Integer getStatTotalSize() {
    return statTotalSize;
  }

   /**
   * Get statSizeOnCache
   * @return statSizeOnCache
  **/
  @ApiModelProperty(example = "6899417088", value = "")
  public Integer getStatSizeOnCache() {
    return statSizeOnCache;
  }

  public Container guestRight(GuestRightEnum guestRight) {
    this.guestRight = guestRight;
    return this;
  }

   /**
   * Get guestRight
   * @return guestRight
  **/
  @ApiModelProperty(example = "read", value = "")
  public GuestRightEnum getGuestRight() {
    return guestRight;
  }

  public void setGuestRight(GuestRightEnum guestRight) {
    this.guestRight = guestRight;
  }

   /**
   * Get lastUpdate
   * @return lastUpdate
  **/
  @ApiModelProperty(example = "2019-08-05T14:24:15.000Z", value = "")
  public String getLastUpdate() {
    return lastUpdate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Container container = (Container) o;
    return Objects.equals(this.id, container.id) &&
        Objects.equals(this.name, container.name) &&
        Objects.equals(this.comment, container.comment) &&
        Objects.equals(this.quotaTotalSize, container.quotaTotalSize) &&
        Objects.equals(this.quotaOnCache, container.quotaOnCache) &&
        Objects.equals(this.statTotalFiles, container.statTotalFiles) &&
        Objects.equals(this.statTotalSize, container.statTotalSize) &&
        Objects.equals(this.statSizeOnCache, container.statSizeOnCache) &&
        Objects.equals(this.guestRight, container.guestRight) &&
        Objects.equals(this.lastUpdate, container.lastUpdate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, comment, quotaTotalSize, quotaOnCache, statTotalFiles, statTotalSize, statSizeOnCache, guestRight, lastUpdate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Container {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    quotaTotalSize: ").append(toIndentedString(quotaTotalSize)).append("\n");
    sb.append("    quotaOnCache: ").append(toIndentedString(quotaOnCache)).append("\n");
    sb.append("    statTotalFiles: ").append(toIndentedString(statTotalFiles)).append("\n");
    sb.append("    statTotalSize: ").append(toIndentedString(statTotalSize)).append("\n");
    sb.append("    statSizeOnCache: ").append(toIndentedString(statSizeOnCache)).append("\n");
    sb.append("    guestRight: ").append(toIndentedString(guestRight)).append("\n");
    sb.append("    lastUpdate: ").append(toIndentedString(lastUpdate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

