/*
 * Nodeum API
 * Nodeum API  # Filter parameters When browsing a list of items, multiple filter parameters may be applied. Some operators can be added to the value as a prefix:  - `=` value is equal. Default operator, may be omitted  - `!=` value is different  - `>` greater than  - `>=` greater than or equal  - `<` lower than  - `>=` lower than or equal  - `><` included in list, items should be separated by `|`  - `!><` not included in list, items should be separated by `|`  - `~` pattern matching, may include `%` (any characters) and `_` (one character)  - `!~` pattern not matching, may include `%` (any characters) and `_` (one character)  
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * NodeumFile
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-09-16T09:57:17.206Z")
public class NodeumFile {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("parent")
  private Integer parent = null;

  /**
   * Gets or Sets type
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    FILE("file"),
    
    FOLDER("folder");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String text) {
      for (TypeEnum b : TypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return TypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("type")
  private TypeEnum type = null;

  @SerializedName("permission")
  private Integer permission = null;

  @SerializedName("size")
  private Integer size = null;

  @SerializedName("change_date")
  private String changeDate = null;

  @SerializedName("modification_date")
  private String modificationDate = null;

  @SerializedName("access_date")
  private String accessDate = null;

  @SerializedName("uid")
  private Integer uid = null;

  @SerializedName("gid")
  private Integer gid = null;

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "105", value = "")
  public Integer getId() {
    return id;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "my-file.txt", value = "")
  public String getName() {
    return name;
  }

   /**
   * Get parent
   * @return parent
  **/
  @ApiModelProperty(example = "100", value = "")
  public Integer getParent() {
    return parent;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "file", value = "")
  public TypeEnum getType() {
    return type;
  }

   /**
   * Get permission
   * @return permission
  **/
  @ApiModelProperty(example = "100666", value = "")
  public Integer getPermission() {
    return permission;
  }

   /**
   * Get size
   * @return size
  **/
  @ApiModelProperty(example = "1063457", value = "")
  public Integer getSize() {
    return size;
  }

   /**
   * Get changeDate
   * @return changeDate
  **/
  @ApiModelProperty(example = "2018-12-10T08:33:47.000Z", value = "")
  public String getChangeDate() {
    return changeDate;
  }

   /**
   * Get modificationDate
   * @return modificationDate
  **/
  @ApiModelProperty(example = "2018-12-10T15:29:23.000Z", value = "")
  public String getModificationDate() {
    return modificationDate;
  }

   /**
   * Get accessDate
   * @return accessDate
  **/
  @ApiModelProperty(example = "2018-12-10T15:27:51.000Z", value = "")
  public String getAccessDate() {
    return accessDate;
  }

   /**
   * Get uid
   * @return uid
  **/
  @ApiModelProperty(example = "1000", value = "")
  public Integer getUid() {
    return uid;
  }

   /**
   * Get gid
   * @return gid
  **/
  @ApiModelProperty(example = "1000", value = "")
  public Integer getGid() {
    return gid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NodeumFile nodeumFile = (NodeumFile) o;
    return Objects.equals(this.id, nodeumFile.id) &&
        Objects.equals(this.name, nodeumFile.name) &&
        Objects.equals(this.parent, nodeumFile.parent) &&
        Objects.equals(this.type, nodeumFile.type) &&
        Objects.equals(this.permission, nodeumFile.permission) &&
        Objects.equals(this.size, nodeumFile.size) &&
        Objects.equals(this.changeDate, nodeumFile.changeDate) &&
        Objects.equals(this.modificationDate, nodeumFile.modificationDate) &&
        Objects.equals(this.accessDate, nodeumFile.accessDate) &&
        Objects.equals(this.uid, nodeumFile.uid) &&
        Objects.equals(this.gid, nodeumFile.gid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, parent, type, permission, size, changeDate, modificationDate, accessDate, uid, gid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NodeumFile {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    permission: ").append(toIndentedString(permission)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    changeDate: ").append(toIndentedString(changeDate)).append("\n");
    sb.append("    modificationDate: ").append(toIndentedString(modificationDate)).append("\n");
    sb.append("    accessDate: ").append(toIndentedString(accessDate)).append("\n");
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("    gid: ").append(toIndentedString(gid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

