/*
 * Nodeum API
 * Nodeum API  # Filter parameters When browsing a list of items, multiple filter parameters may be applied. Some operators can be added to the value as a prefix:  - `=` value is equal. Default operator, may be omitted  - `!=` value is different  - `>` greater than  - `>=` greater than or equal  - `<` lower than  - `>=` lower than or equal  - `><` included in list, items should be separated by `|`  - `!><` not included in list, items should be separated by `|`  - `~` pattern matching, may include `%` (any characters) and `_` (one character)  - `!~` pattern not matching, may include `%` (any characters) and `_` (one character)  
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Error;
import io.swagger.client.model.TaskExecution;
import io.swagger.client.model.TaskExecutionCollection;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TaskExecutionsApi
 */
@Ignore
public class TaskExecutionsApiTest {

    private final TaskExecutionsApi api = new TaskExecutionsApi();

    
    /**
     * Lists all task executions.
     *
     * **API Key Scope**: task_executions / index
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void indexTaskExecutionsTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        List<String> sortBy = null;
        String id = null;
        String taskId = null;
        String name = null;
        String type = null;
        String status = null;
        String logTime = null;
        String jobStarted = null;
        String jobFinished = null;
        String toProcessSize = null;
        String processedSize = null;
        String toProcessFiles = null;
        String processedFiles = null;
        String finalizedFiles = null;
        String estimationTime = null;
        String bandwidth = null;
        TaskExecutionCollection response = api.indexTaskExecutions(limit, offset, sortBy, id, taskId, name, type, status, logTime, jobStarted, jobFinished, toProcessSize, processedSize, toProcessFiles, processedFiles, finalizedFiles, estimationTime, bandwidth);

        // TODO: test validations
    }
    
    /**
     * Lists all task executions.
     *
     * **API Key Scope**: task_executions / index
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void indexTaskExecutionsByTaskTest() throws ApiException {
        String taskId = null;
        TaskExecutionCollection response = api.indexTaskExecutionsByTask(taskId);

        // TODO: test validations
    }
    
    /**
     * Displays a specific task execution.
     *
     * **API Key Scope**: task_executions / show
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void showTaskExecutionTest() throws ApiException {
        Long taskExecutionId = null;
        TaskExecution response = api.showTaskExecution(taskExecutionId);

        // TODO: test validations
    }
    
    /**
     * Displays a specific task execution.
     *
     * **API Key Scope**: task_executions / show
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void showTaskExecutionByTaskTest() throws ApiException {
        String taskId = null;
        Long taskExecutionId = null;
        TaskExecution response = api.showTaskExecutionByTask(taskId, taskExecutionId);

        // TODO: test validations
    }
    
}
