#!/bin/bash
shopt -s extglob

cd "`dirname \"$0\"`/.."

rm -r -- !("tools"|"LICENSE")

docker run --rm \
    -v ${PWD}:/project \
    openapitools/openapi-generator-cli generate \
    -i https://api.swaggerhub.com/apis/Nodeum/nodeum/2.1.0 \
    -p sortParamsByRequiredFlag \
    -p modelPackage=io.nodeum.client.model \
    -p apiPackage=io.nodeum.client.api \
    -p invokerPackage=io.nodeum.client \
    -p groupId=io.nodeum \
    -p artifactId=nodeum-sdk \
    -p artifactVersion=1.84.0 \
    -p artifactUrl=https://github.com/nodeum-io/nodeum-sdk-java \
    -p artifactDescription="Nodeum API Reference" \
    -p scmConnection=scm:git:git@github.com:nodeum-io/nodeum-sdk-java \
    -p scmDeveloperConnection=scm:git:git@github.com:nodeum-io/nodeum-sdk-java \
    -p scmUrl=https://github.com/nodeum-io/nodeum-sdk-java \
    -p developerName=MT-C \
    -p developerEmail=support@mt-c.com \
    -p developerOrganization=MT-C \
    -p developerOrganizationUrl=https://mt-c.com/ \
    -p licenseName="MIT License" \
    -p licenseUrl=https://opensource.org/licenses/MIT \
    -g java \
    -o /project/
