/*
 * Nodeum API
 * # About  This document describes the Nodeum API version 2:  If you are looking for any information about the product itself, reach the product website https://www.nodeum.io. You can also contact us at this email address : info@nodeum.io  # Filter parameters When browsing a list of items, multiple filter parameters may be applied. Some operators can be added to the value as a prefix:  - `=` value is equal. Default operator, may be omitted  - `!=` value is different  - `>` greater than  - `>=` greater than or equal  - `<` lower than  - `>=` lower than or equal  - `><` included in list, items should be separated by `|`  - `!><` not included in list, items should be separated by `|`  - `~` pattern matching, may include `%` (any characters) and `_` (one character)  - `!~` pattern not matching, may include `%` (any characters) and `_` (one character)  
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.nodeum.client.api;

import io.nodeum.client.ApiException;
import io.nodeum.client.model.ActiveJobStatus;
import io.nodeum.client.model.Error;
import io.nodeum.client.model.MountStatus;
import io.nodeum.client.model.NasShare;
import io.nodeum.client.model.NasShareCollection;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NasSharesApi
 */
@Ignore
public class NasSharesApiTest {

    private final NasSharesApi api = new NasSharesApi();

    
    /**
     * Creates a new NAS share.
     *
     * **API Key Scope**: nas_shares / create
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createNasShareByNasTest() throws ApiException {
        String nasId = null;
        NasShare nasShareBody = null;
        NasShare response = api.createNasShareByNas(nasId, nasShareBody);

        // TODO: test validations
    }
    
    /**
     * Destroys a specific NAS share.
     *
     * **API Key Scope**: nas_shares / destroy
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void destroyNasShareTest() throws ApiException {
        String nasShareId = null;
        api.destroyNasShare(nasShareId);

        // TODO: test validations
    }
    
    /**
     * Destroys a specific NAS share.
     *
     * **API Key Scope**: nas_shares / destroy
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void destroyNasShareByNasTest() throws ApiException {
        String nasId = null;
        String nasShareId = null;
        api.destroyNasShareByNas(nasId, nasShareId);

        // TODO: test validations
    }
    
    /**
     * Destroys a specific NAS share.
     *
     * **API Key Scope**: nas_shares / destroy
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void destroyNasShareByPoolTest() throws ApiException {
        String poolId = null;
        String nasShareId = null;
        api.destroyNasShareByPool(poolId, nasShareId);

        // TODO: test validations
    }
    
    /**
     * Lists all NAS shares.
     *
     * **API Key Scope**: nas_shares / index   Optional API Key Explicit Scope: nas_shares / get_password
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void indexNasSharesTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        List<String> sortBy = null;
        String id = null;
        String name = null;
        String path = null;
        String options = null;
        String username = null;
        String nasId = null;
        String poolId = null;
        NasShareCollection response = api.indexNasShares(limit, offset, sortBy, id, name, path, options, username, nasId, poolId);

        // TODO: test validations
    }
    
    /**
     * Lists all NAS shares.
     *
     * **API Key Scope**: nas_shares / index   Optional API Key Explicit Scope: nas_shares / get_password
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void indexNasSharesByNasTest() throws ApiException {
        String nasId = null;
        Integer limit = null;
        Integer offset = null;
        List<String> sortBy = null;
        String id = null;
        String name = null;
        String path = null;
        String options = null;
        String username = null;
        String poolId = null;
        NasShareCollection response = api.indexNasSharesByNas(nasId, limit, offset, sortBy, id, name, path, options, username, poolId);

        // TODO: test validations
    }
    
    /**
     * Lists all NAS shares from pool.
     *
     * **API Key Scope**: nas_shares / index   Optional API Key Explicit Scope: nas_shares / get_password
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void indexNasSharesByPoolTest() throws ApiException {
        String poolId = null;
        Integer limit = null;
        Integer offset = null;
        List<String> sortBy = null;
        String id = null;
        String name = null;
        String path = null;
        String options = null;
        String username = null;
        String nasId = null;
        NasShareCollection response = api.indexNasSharesByPool(poolId, limit, offset, sortBy, id, name, path, options, username, nasId);

        // TODO: test validations
    }
    
    /**
     * Get mount status of NAS Share.
     *
     * **API Key Scope**: nas_shares / mount_status
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void mountStatusNasShareTest() throws ApiException {
        String nasShareId = null;
        MountStatus response = api.mountStatusNasShare(nasShareId);

        // TODO: test validations
    }
    
    /**
     * Get mount status of NAS Share.
     *
     * **API Key Scope**: nas_shares / mount_status
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void mountStatusNasShareByNasTest() throws ApiException {
        String nasId = null;
        String nasShareId = null;
        MountStatus response = api.mountStatusNasShareByNas(nasId, nasShareId);

        // TODO: test validations
    }
    
    /**
     * Get mount status of NAS Share.
     *
     * **API Key Scope**: nas_shares / mount_status
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void mountStatusNasShareByPoolTest() throws ApiException {
        String poolId = null;
        String nasShareId = null;
        MountStatus response = api.mountStatusNasShareByPool(poolId, nasShareId);

        // TODO: test validations
    }
    
    /**
     * Displays a specific NAS share.
     *
     * **API Key Scope**: nas_shares / show   Optional API Key Explicit Scope: nas_shares / get_password
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void showNasShareTest() throws ApiException {
        String nasShareId = null;
        NasShare response = api.showNasShare(nasShareId);

        // TODO: test validations
    }
    
    /**
     * Displays a specific NAS share.
     *
     * **API Key Scope**: nas_shares / show   Optional API Key Explicit Scope: nas_shares / get_password
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void showNasShareByNasTest() throws ApiException {
        String nasId = null;
        String nasShareId = null;
        NasShare response = api.showNasShareByNas(nasId, nasShareId);

        // TODO: test validations
    }
    
    /**
     * Displays a specific NAS share.
     *
     * **API Key Scope**: nas_shares / show   Optional API Key Explicit Scope: nas_shares / get_password
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void showNasShareByPoolTest() throws ApiException {
        String poolId = null;
        String nasShareId = null;
        NasShare response = api.showNasShareByPool(poolId, nasShareId);

        // TODO: test validations
    }
    
    /**
     * Test an unsaved NAS Share.
     *
     * **API Key Scope**: nas_shares / test
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void testNasShareTest() throws ApiException {
        String nasId = null;
        NasShare nasShareBody = null;
        ActiveJobStatus response = api.testNasShare(nasId, nasShareBody);

        // TODO: test validations
    }
    
    /**
     * Check result of a NAS Share test job.
     *
     * **API Key Scope**: nas_shares / test
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void testResultNasShareTest() throws ApiException {
        String nasId = null;
        String jobId = null;
        ActiveJobStatus response = api.testResultNasShare(nasId, jobId);

        // TODO: test validations
    }
    
    /**
     * Updates a specific NAS share.
     *
     * **API Key Scope**: nas_shares / update
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateNasShareTest() throws ApiException {
        String nasShareId = null;
        NasShare nasShareBody = null;
        NasShare response = api.updateNasShare(nasShareId, nasShareBody);

        // TODO: test validations
    }
    
    /**
     * Updates a specific NAS share.
     *
     * **API Key Scope**: nas_shares / update
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateNasShareByNasTest() throws ApiException {
        String nasId = null;
        String nasShareId = null;
        NasShare nasShareBody = null;
        NasShare response = api.updateNasShareByNas(nasId, nasShareId, nasShareBody);

        // TODO: test validations
    }
    
    /**
     * Updates a specific NAS share.
     *
     * **API Key Scope**: nas_shares / update
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateNasShareByPoolTest() throws ApiException {
        String poolId = null;
        String nasShareId = null;
        NasShare nasShareBody = null;
        NasShare response = api.updateNasShareByPool(poolId, nasShareId, nasShareBody);

        // TODO: test validations
    }
    
}
